export const STARPORT_TYPE = {
    A: 'Excellent',
    B: 'Good',
    C: 'Routine',
    D: 'Poor',
    E: 'Frontier',
    X: 'None',
};

export const ATMOSPHERE_TYPE = {
    '0': 'None',
    '1': 'Trace',
    '2': 'Very Thin',
    '3': 'Very Thin, Tainted',
    '4': 'Thin',
    '5': 'Thin, Tainted',
    '6': 'Standard',
    '7': 'Standard, Tainted',
    '8': 'Dense',
    '9': 'Dense, Tainted',
    A: 'Exotic',
    B: 'Corrosive',
    C: 'Insidious',
    D: 'Dense, High',
    E: 'Thin, Low',
    F: 'Unusual',
};

export const HYDROGRAPHICS_TYPE = {
    '0': '0%',
    '1': '10%',
    '2': '20%',
    '3': '30%',
    '4': '40%',
    '5': '50%',
    '6': '60%',
    '7': '70%',
    '8': '80%',
    '9': '90%',
    A: '100%',
};

export const POPULATION_TYPE = {
    '0': 'None',
    '1': 'Few',
    '2': 'Hundreds',
    '3': 'Thousands',
    '4': 'Tens of thousands',
    '5': 'Hundreds of thousands',
    '6': 'Millions',
    '7': 'Tens of millions',
    '8': 'Hundreds of millions',
    '9': 'Billions',
    A: 'Tens of billions',
    B: 'Hundreds of billions',
    C: 'Trillions',
};

export const GOVERNMENT_TYPE = {
    '0': 'None',
    '1': 'Company/Corporation',
    '2': 'Participating Democracy',
    '3': 'Self-Perpetuating Oligarchy',
    '4': 'Representative Democracy',
    '5': 'Feudal Technocracy',
    '6': 'Captive Government',
    '7': 'Balkanisation',
    '8': 'Civil Service Bureaucracy',
    '9': 'Impersonal Bureaucracy',
    A: 'Charismatic Dictator',
    B: 'Non-Charismatic Leader',
    C: 'Charismatic Oligarchy',
    D: 'Religious Dictatorship',
    E: 'Religious Autocracy',
    F: 'Totalitarian Oligarchy',
};

export const LAW_LEVEL_TYPE = {
    '0': 'No Law',
    '1': 'Low Law',
    '2': 'Low Law',
    '3': 'Low Law',
    '4': 'Moderate Law',
    '5': 'Moderate Law',
    '6': 'Moderate Law',
    '7': 'High Law',
    '8': 'High Law',
    '9': 'Extreme Law',
    A: 'Full Censorship',
    B: 'Paramilitary Law',
    C: 'Full Surveillance',
    D: 'Religious Law',
    E: 'Total Control',
    F: 'Prison State',
};

export const TECH_LEVEL_TYPE = {
    '0': 'Stone Age',
    '1': 'Bronze/Iron Age',
    '2': 'Medieval',
    '3': 'Renaissance',
    '4': 'Industrial Revolution',
    '5': 'Early Industrial',
    '6': 'Mechanised',
    '7': 'Pre-Stellar',
    '8': 'Early Stellar',
    '9': 'Average Stellar',
    A: 'Interstellar Community',
    B: 'High Stellar',
    C: 'Very High Stellar',
    D: 'Extreme Stellar',
    E: 'Post-Scarcity',
    F: 'Transcendent',
};