export const STARPORT_TYPE = {
    A: "Excellent",
    B: "Good",
    C: "Routine",
    D: "Poor",
    E: "Frontier",
    X: "No Starport"
};

export const SIZE = {
    "1": "1,600km",
    "2": "3,200km, Triton, Luna, Europa",
    "3": "4,800km, Mercury, Ganymede",
    "4": "6,400km, Mars",
    "5": "8,000km",
    "6": "9,600km",
    "7": "11,200km",
    "8": "12,800km Earth",
    "9": "14,400km",
    A: "16,000km"
};

export const ATMOSPHERE_TYPE = {
    '0': 'None',
    '1': 'Trace',
    '2': 'Very Thin',
    '3': 'Very Thin, Tainted',
    '4': 'Thin',
    '5': 'Thin, Tainted',
    '6': 'Standard',
    '7': 'Standard, Tainted',
    '8': 'Dense',
    '9': 'Dense, Tainted',
    A: 'Exotic',
    B: 'Corrosive',
    C: 'Insidious',
    D: 'Dense, High',
    E: 'Thin, Low',
    F: 'Unusual',
};

export const HYDROGRAPHICS_TYPE = {
    '0': '0%',
    '1': '10%',
    '2': '20%',
    '3': '30%',
    '4': '40%',
    '5': '50%',
    '6': '60%',
    '7': '70%',
    '8': '80%',
    '9': '90%',
    A: '100%',
};

export const POPULATION_TYPE = {
    '0': 'None',
    '1': 'Few',
    '2': 'Hundreds',
    '3': 'Thousands',
    '4': 'Tens of thousands',
    '5': 'Hundreds of thousands',
    '6': 'Millions',
    '7': 'Tens of millions',
    '8': 'Hundreds of millions',
    '9': 'Billions',
    A: 'Tens of billions',
    B: 'Hundreds of billions',
    C: 'Trillions',
};

export const GOVERNMENT_TYPE = {
    '0': 'None',
    '1': 'Company/Corporation',
    '2': 'Participating Democracy',
    '3': 'Self-Perpetuating Oligarchy',
    '4': 'Representative Democracy',
    '5': 'Feudal Technocracy',
    '6': 'Captive Government',
    '7': 'Balkanisation',
    '8': 'Civil Service Bureaucracy',
    '9': 'Impersonal Bureaucracy',
    A: 'Charismatic Dictator',
    B: 'Non-Charismatic Leader',
    C: 'Charismatic Oligarchy',
    D: 'Religious Dictatorship',
    E: 'Religious Autocracy',
    F: 'Totalitarian Oligarchy',
};

export const LAW_LEVEL_TYPE = {
    '0': 'No Law',
    '1': 'Low Law',
    '2': 'Low Law',
    '3': 'Low Law',
    '4': 'Moderate Law',
    '5': 'Moderate Law',
    '6': 'Moderate Law',
    '7': 'High Law',
    '8': 'High Law',
    '9': 'Extreme Law',
    A: 'Full Censorship',
    B: 'Paramilitary Law',
    C: 'Full Surveillance',
    D: 'Religious Law',
    E: 'Total Control',
    F: 'Prison State',
};

export const TECH_LEVEL_TYPE = {
    '0': 'Stone Age',
    '1': 'Bronze/Iron Age',
    '2': 'Medieval',
    '3': 'Renaissance',
    '4': 'Industrial Revolution',
    '5': 'Early Industrial',
    '6': 'Mechanised',
    '7': 'Pre-Stellar',
    '8': 'Early Stellar',
    '9': 'Average Stellar',
    A: 'Interstellar Community',
    B: 'High Stellar',
    C: 'Very High Stellar',
    D: 'Extreme Stellar',
    E: 'Post-Scarcity',
    F: 'Transcendent',
};

export const ALLEGIANCES = {
    "As": "Aslan Hierate",
    "At": "Anubian Trade Coalition",
    "Bs": "Belgardian Sojurnate",
    "Cs": "Client State",
    "Dr": "Droyne World",
    "Hv": "Hive Federation",
    "Im": "Imperium",
    "Kk": "K'kree Two Thousand Worlds empire",
    "Na": "",
    "So": "Solomani Confederation",
    "Zh": "Consulate",
    "Cw": "Chirper World",
    "Dd": "Domain of Deneb",
    "Fd": "Federation of Daibei",
    "Fi": "Federation of Ilelish",
    "La": "League of Antares",
    "Li": "Lucan's Imperium",
    "Ma": "Margaret's Stronghold",
    "Rv": "Restored Vilani Empire",
    "St": "Strephon's Imperium",
    "Wi": "Wilds",
    "Zc": "Zodia Colonies",
    "Ca": "Carrillian Assembly",
    "Pc": "Principality of Caledon",
    "Ct": "Carter Technocracy",
    "Cl": "Council of Leh Perash",
    "Cu": "Cytralin Unity",
    "Dc": "Confederation of Duncinae",
    "Fh": "Federation of Heron",
    "Fl": "Florian League",
    "Gr": "Gamma Republic",
    "Gm": "Grand Duchy of Marlheim",
    "Gd": "Grand Duchy of Stoner",
    "Go": "Gerontocracy of Ormine",
    "Ge": "Glorious Empire",
    "Gf": "Glimmerdrift Federation",
    "Gc": "Gniivi Collective",
    "Id": "Islaiat Dominate",
    "Ju": "Imperium",
    "Kl": "Khuur League",
    "Lr": "Loyal Nineworlds Republic",
    "Lc": "Lanyard Colonies",
    "Me": "Maskai Empire",
    "Ow": "Outcasts of the Whispering Sky",
    "Ra": "Ral Ranta",
    "Sf": "Senlis Foederate",
    "Sc": "Strend Cluster",
    "Sw": "Sword Worlds Confederation",
    "Ta": "Tealou Arlaoh (Aslan independent clan, non-outcast)",
    "Uh": "Union of Harmony",
    "V4": "40th Squadron (Ekhelle Ksafi)",
    "Ac": "Anti-Rukh Coalition (Gnoerrgh Rukh Lloell)",
    "Ua": "United Followers of Augurgh",
    "Ba": "Bakne Alliance",
    "Ck": "Commonality of Kedzudh (Kedzudh Aeng)",
    "Df": "Dzarrgh Federate",
    "Pg": "Pact of Gaerr (Gaerr Thue)",
    "Rs": "Rranglloez Stronghold",
    "Wr": "Worlds of Leader Rukh (Rukh Aegz)",
    "Sd": "Saeknouth Dependency (Saeknouth Igz)",
    "Se": "Society of Equals (Dzen Aeng Kho)",
    "Te": "Thirz Empire (Thirz Uerra)",
    "Ur": "Urukhu",
    "Ev": "Empire of Varroerth",
    "Pw": "People of Wanz",
    "Wp": "Windhorn Pact of Two"
};

export const TRADE_CODES = {
    Ag: "Agricultural",
    As: "Asteroid",
    Ba: "Barren",
    De: "Desert",
    Fl: "Fluid Oceans",
    Ga: "Garden",
    Hi: "High Population",
    Ht: "High Tech",
    Ic: "Ice-Capped",
    In: "Industrial",
    Lo: "Low Population",
    Lt: "Low Tech",
    Na: "Non-Agricultural",
    Ni: "Non-Industrial",
    Po: "Poor",
    Ri: "Rich",
    Va: "Vacuum",
    Wa: "Water World"
};
